# Generated by Django 4.1.1 on 2022-09-14 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=1000, null=True)),
                ('category_url', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ['category_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=1000, null=True)),
                ('product_image', models.TextField(max_length=1000, null=True)),
                ('product_url', models.TextField(max_length=1000, null=True)),
                ('product_ingredients', models.TextField(max_length=1000, null=True)),
                ('product_nutriscore', models.TextField(max_length=1000)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.category')),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('substitute_id', models.AutoField(primary_key=True, serialize=False)),
                ('substitute_name', models.TextField(max_length=1000, null=True)),
                ('substitute_image', models.TextField(max_length=1000, null=True)),
                ('substitute_nutriscore', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['substitute_id'],
            },
        ),
    ]
