# Generated by Django 3.2.12 on 2022-04-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purbeurre_website.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
