# Generated by Django 3.2.12 on 2022-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0004_auto_20220406_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
    ]
