# Generated by Django 3.2.12 on 2022-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0005_accountcreationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_name', models.CharField(max_length=100, null=True)),
                ('substitute_nutriscore', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountCreationForm',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
