# Generated by Django 3.2.12 on 2022-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0006_auto_20220603_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='substitute_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
