# Generated by Django 3.2.12 on 2022-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0007_auto_20220603_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
