# Generated by Django 3.2.12 on 2022-06-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0008_alter_substitute_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitute',
            old_name='id',
            new_name='substitute_id',
        ),
    ]
