# Generated by Django 3.2.12 on 2022-06-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0010_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
