# Generated by Django 3.2.12 on 2022-06-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0011_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['substitute_id']},
        ),
        migrations.AlterModelOptions(
            name='substitute',
            options={'ordering': ['substitute_id']},
        ),
    ]
