# Generated by Django 3.2.12 on 2022-06-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0014_delete_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
