# Generated by Django 3.2.12 on 2022-06-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0016_basket_substitute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
