# Generated by Django 3.2.12 on 2022-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purbeurre_website', '0017_auto_20220616_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('substitute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('substitute_name', models.CharField(max_length=100, null=True)),
                ('substitute_image', models.CharField(max_length=100, null=True)),
                ('substitute_url', models.CharField(max_length=100, null=True)),
                ('substitute_nutriscore', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['substitute_id'],
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('substitute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('substitute_name', models.CharField(max_length=100, null=True)),
                ('substitute_image', models.CharField(max_length=100, null=True)),
                ('substitute_url', models.CharField(max_length=100, null=True)),
                ('substitute_nutriscore', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['substitute_id'],
            },
        ),
    ]
