# Generated by Django 3.2.12 on 2022-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0018_basket_substitute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_image', models.CharField(max_length=100, null=True)),
                ('product_url', models.CharField(max_length=100, null=True)),
                ('product_nutriscore', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
