# Generated by Django 3.2.12 on 2022-06-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0021_basket_product_substitute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='reference_product_foreign_key',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
