# Generated by Django 3.2.12 on 2022-06-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0023_basket_category_product_substitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_key',
        ),
    ]
