# Generated by Django 3.2.12 on 2022-06-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0028_basket_category_product_substitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.category'),
        ),
    ]
