# Generated by Django 3.2.12 on 2022-06-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0031_product_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.category'),
        ),
    ]
