# Generated by Django 3.2.12 on 2022-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0034_remove_substitute_reference_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
