# Generated by Django 3.2.12 on 2022-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0035_product_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='substitute_ingredients',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_ingredients',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
