# Generated by Django 3.2.12 on 2022-07-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0036_auto_20220701_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_key',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
