# Generated by Django 3.2.12 on 2022-07-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0038_basket_category_product_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='category_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.category'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='category_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.category'),
        ),
    ]
