# Generated by Django 3.2.12 on 2022-07-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0039_auto_20220711_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='category_key',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_key',
            new_name='category_id',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
