# Generated by Django 3.2.12 on 2022-07-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0041_favourite_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
