# Generated by Django 3.2.12 on 2022-07-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_website', '0042_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('substitute_id', models.AutoField(primary_key=True, serialize=False)),
                ('substitute_name', models.CharField(max_length=100, null=True)),
                ('substitute_image', models.CharField(max_length=100, null=True)),
                ('substitute_nutriscore', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre_website.user')),
            ],
            options={
                'ordering': ['substitute_id'],
            },
        ),
    ]
